export const pl = {
  brand: "twoje kolory",
  navStart: "Zrób test",
  backHome: "Wróć na stronę główną",
  back: "Wstecz",
  next: "Dalej",
  landing: {
    heroAlt: "Kobieta trzymająca kolorowe próbki tkanin",
    eyebrow: "ANALIZA KOLORYSTYCZNA ONLINE",
    title: "Odkryj swoje kolory w 60 sekund",
    subtitle: "Przestań kupować ubrania, w których wyglądasz na zmęczoną.",
    cta: "Zacznij test",
    note: "Szybki test · Jedno zdjęcie · Twoja paleta",
    stepsEyebrow: "TO NAPRAWDĘ PROSTE",
    stepsTitle: "Twój kolor. Twoja pewność siebie.",
    steps: [
      { title: "Odpowiedz na 6 pytań", description: "Kilka wskazówek o Tobie pomoże nam lepiej zrozumieć Twoją urodę." },
      { title: "Dodaj selfie", description: "Naturalne zdjęcie w dziennym świetle wystarczy, by zacząć analizę." },
      { title: "Poznaj swoją paletę", description: "Odkryj kolory, które podkreślają to, co w Tobie najpiękniejsze." },
    ],
    previewEyebrow: "MAŁA ZAPOWIEDŹ",
    previewTitle: "Kolory, które są naprawdę Twoje.",
    previewText: "Wyobraź sobie garderobę, w której wszystko po prostu do Ciebie pasuje.",
    previewLabel: "Przykładowa paleta",
    previewSeason: "Ciepła Wiosna",
    previewCardText: "Świeże, świetliste barwy, które ożywiają cerę i dodają blasku.",
    previewCta: "Sprawdź swoje kolory",
  },
  quiz: {
    eyebrow: "TWÓJ MAŁY PORTRET",
    progress: "Pytanie",
    of: "z",
    title: "Zacznijmy od Ciebie.",
    subtitle: "Wybierz odpowiedź, która najbardziej do Ciebie pasuje.",
    questions: [
      { title: "Jaki jest Twój naturalny kolor włosów?", answers: ["Jasny blond", "Ciemny blond lub jasny brąz", "Brązowe", "Czarne", "Rude"] },
      { title: "Jaki kolor mają Twoje oczy?", answers: ["Niebieskie lub szare", "Zielone", "Piwne", "Brązowe"] },
      { title: "Jaki kolor mają żyłki na Twoim nadgarstku?", answers: ["Niebieski lub fioletowy", "Zielony", "Trudno powiedzieć — mieszany"] },
      { title: "W jakiej biżuterii czujesz się najlepiej?", answers: ["Złotej", "Srebrnej", "W obu"] },
      { title: "Jak reaguje Twoja skóra na słońce?", answers: ["Łatwo się rumienię lub opalam na czerwono", "Łatwo się opalam", "Najpierw się rumienię, potem opalam"] },
      { title: "W jakich kolorach słyszysz najwięcej komplementów?", answers: ["Ciepłych i jasnych", "Chłodnych i delikatnych", "Ciepłych i głębokich", "Wyrazistych i kontrastowych"] },
    ],
  },
  photo: {
    eyebrow: "OSTATNI KROK",
    title: "Pokaż nam swoją naturalną stronę.",
    subtitle: "Dodaj wyraźne selfie, abyśmy mogły dobrać kolory do Twojej urody.",
    tipsTitle: "Najlepsze zdjęcie zrobisz tak:",
    tips: ["W dziennym świetle", "Bez makijażu", "Z widocznymi włosami", "Bez filtra"],
    upload: "Dodaj swoje zdjęcie",
    uploadHint: "Wybierz z galerii lub zrób zdjęcie telefonem",
    change: "Zmień zdjęcie",
    consent: "Zgadzam się na przetwarzanie mojego zdjęcia przez AI w celu wykonania analizy. Zdjęcie zostanie automatycznie usunięte po 24 godzinach.",
    submit: "Analizuj moje kolory",
    loadingTitle: "Szukamy Twoich kolorów…",
    loadingText: "Przyglądamy się detalom, które czynią Cię wyjątkową.",
    retakeTitle: "Spróbujmy z innym zdjęciem.",
    retakeText: "Nie udało nam się wystarczająco dobrze odczytać kolorów. Zrób zdjęcie ponownie, korzystając ze wskazówek poniżej.",
    retakeButton: "Wybierz inne zdjęcie",
    invalidFile: "Wybierz zdjęcie w formacie obrazu.",
  },
  result: {
    eyebrow: "TWOJA ANALIZA KOLORYSTYCZNA",
    familyPrefix: "Jesteś",
    familyForms: { Wiosna: "Wiosną", Lato: "Latem", "Jesień": "Jesienią", Zima: "Zimą" },
    teaserText: "Twój dokładny typ to jeden z 3 typów Lata. Odblokuj pełny wynik.",
    teaserTextByFamily: {
      Wiosna: "Twój dokładny typ to jeden z 3 typów Wiosny. Odblokuj pełny wynik.",
      Lato: "Twój dokładny typ to jeden z 3 typów Lata. Odblokuj pełny wynik.",
      "Jesień": "Twój dokładny typ to jeden z 3 typów Jesieni. Odblokuj pełny wynik.",
      Zima: "Twój dokładny typ to jeden z 3 typów Zimy. Odblokuj pełny wynik.",
    },
    teaserPalette: "Pierwsze kolory z Twojej palety",
    hidden: "Twoja pełna paleta czeka na odkrycie",
    unlockTitle: "Poznaj całą swoją paletę.",
    unlockText: "Odkryj swój dokładny typ, wszystkie najlepsze kolory i odcienie, których warto unikać.",
    legalConsent: "Zgadzam się na natychmiastowe dostarczenie treści cyfrowej i przyjmuję do wiadomości utratę 14-dniowego prawa do odstąpienia od umowy.",
    unlock: "Odblokuj pełny wynik – 39 zł",
    best: "Twoje najlepsze kolory",
    avoid: "Kolory, których warto unikać",
    neutrals: "Twoje kolory bazowe",
    download: "Pobierz kartę kolorów",
    downloadPlaceholder: "Pobieranie karty kolorów będzie dostępne wkrótce.",
    missing: "Nie znaleziono wyniku.",
    loading: "Otwieramy Twój wynik…",
  },
  footer: {
    trust: "Analiza wykonywana przez AI",
    note: "Twoje kolory, po Twojemu.",
    copyright: "© 2026 Twoje Kolory",
  },
  legal: {
    terms: { label: "Regulamin", title: "Regulamin", text: "Ta strona jest wersją demonstracyjną. Pełny regulamin zostanie udostępniony przed uruchomieniem usługi." },
    privacy: { label: "Polityka prywatności", title: "Polityka prywatności", text: "Ta strona jest wersją demonstracyjną. Pełna polityka prywatności zostanie udostępniona przed uruchomieniem usługi." },
    cookies: { label: "Polityka cookies", title: "Polityka cookies", text: "Ta strona jest wersją demonstracyjną. Obecnie zapisujemy tylko Twój wybór dotyczący plików cookies w przeglądarce." },
    withdrawal: { label: "Odstąp od umowy", title: "Odstąp od umowy", text: "Ta strona jest wersją demonstracyjną. Informacje o odstąpieniu od umowy zostaną udostępnione przed uruchomieniem usługi." },
  },
  cookies: {
    title: "Dbamy o Twoją prywatność",
    text: "Używamy niezbędnych plików cookies. Możesz wybrać, czy zgadzasz się również na pozostałe.",
    accept: "Akceptuj wszystkie",
    necessary: "Tylko niezbędne",
  },
  mock: {
    seasons: {
      summer: { season_pl: "Chłodne Lato", season_en: "Cool Summer", family: "Lato" as const, description: "Twoja uroda rozkwita w chłodnych, łagodnych barwach. Przygaszony błękit, malinowy róż i delikatny lawendowy podkreślają naturalną harmonię Twoich rysów." },
      spring: { season_pl: "Ciepła Wiosna", season_en: "Warm Spring", family: "Wiosna" as const, description: "Promienne, ciepłe odcienie pięknie współgrają z Twoją urodą. Koral, brzoskwinia i świeża zieleń dodadzą Ci naturalnego blasku." },
      autumn: { season_pl: "Ciepła Jesień", season_en: "Warm Autumn", family: "Jesień" as const, description: "Głębokie, ciepłe barwy podkreślają Twoją naturalną wyrazistość. Oliwka, rdza i złoto tworzą harmonijną paletę właśnie dla Ciebie." },
      winter: { season_pl: "Chłodna Zima", season_en: "Cool Winter", family: "Zima" as const, description: "Wyrazisty kontrast i czyste chłodne kolory dodają Twojej urodzie energii. Rubin, szmaragd i granat to Twoi sprzymierzeńcy." },
    },
    palettes: {
      summer: { best: [{ name: "Pudrowy róż", hex: "#DCA9AF" }, { name: "Gołębi błękit", hex: "#8FAFC4" }, { name: "Lawenda", hex: "#A899BF" }, { name: "Malina", hex: "#B05B77" }, { name: "Szałwia", hex: "#9BAFA6" }, { name: "Śliwka", hex: "#786477" }, { name: "Morski", hex: "#528F9D" }, { name: "Chłodny róż", hex: "#C97E9D" }], avoid: [{ name: "Pomarańcz", hex: "#E67930" }, { name: "Musztarda", hex: "#C99A2E" }, { name: "Neonowy koral", hex: "#FB6148" }], neutrals: [{ name: "Miękka biel", hex: "#EEEDE8" }, { name: "Chłodny beż", hex: "#B8AFA8" }, { name: "Grafit", hex: "#555C66" }] },
      spring: { best: [{ name: "Koral", hex: "#E97668" }, { name: "Brzoskwinia", hex: "#F5B88D" }, { name: "Jaskier", hex: "#F5CF62" }, { name: "Turkus", hex: "#53ADA8" }, { name: "Świeża zieleń", hex: "#86A96D" }, { name: "Ciepły róż", hex: "#E99AA2" }, { name: "Mandarynka", hex: "#EFA05A" }, { name: "Akwamaryna", hex: "#85C9BE" }], avoid: [{ name: "Grafit", hex: "#555C66" }, { name: "Chłodny fiolet", hex: "#74639D" }, { name: "Bordo", hex: "#6D3042" }], neutrals: [{ name: "Krem", hex: "#F4E9CF" }, { name: "Camel", hex: "#B99573" }, { name: "Ciepły brąz", hex: "#795B49" }] },
      autumn: { best: [{ name: "Oliwka", hex: "#81865A" }, { name: "Rdza", hex: "#B56849" }, { name: "Musztarda", hex: "#C99A2E" }, { name: "Butelkowa zieleń", hex: "#487265" }, { name: "Terakota", hex: "#BD785F" }, { name: "Miedź", hex: "#B47B55" }, { name: "Burgund", hex: "#803F4A" }, { name: "Petrol", hex: "#3B777C" }], avoid: [{ name: "Lodowy błękit", hex: "#BDD9EA" }, { name: "Neonowy róż", hex: "#F66AAD" }, { name: "Chłodna szarość", hex: "#A8B1BD" }], neutrals: [{ name: "Kość słoniowa", hex: "#EBDFC4" }, { name: "Czekolada", hex: "#60493D" }, { name: "Oliwkowy beż", hex: "#A3997C" }] },
      winter: { best: [{ name: "Rubin", hex: "#A53655" }, { name: "Szmaragd", hex: "#167D72" }, { name: "Kobalt", hex: "#365BAA" }, { name: "Fuksja", hex: "#CB4A91" }, { name: "Granat", hex: "#263F68" }, { name: "Lodowy róż", hex: "#E9B9CC" }, { name: "Śliwka", hex: "#743D69" }, { name: "Biel", hex: "#F5F4F1" }], avoid: [{ name: "Musztarda", hex: "#C99A2E" }, { name: "Pomarańcz", hex: "#E67930" }, { name: "Ciepły beż", hex: "#B99573" }], neutrals: [{ name: "Czysta biel", hex: "#F5F4F1" }, { name: "Czerń", hex: "#28282B" }, { name: "Chłodna szarość", hex: "#9DA4AB" }] },
    },
  },
};