export const pl = {
  brand: "twoje kolory",
  navStart: "Zrób analizę — 39 zł",
  backHome: "Wróć na stronę główną",
  back: "Wstecz",
  next: "Dalej",
  landing: {
    heroAlt: "Naturalny portret kobiety obok jej osobistej cyfrowej palety kolorów",
    eyebrow: "PERSONALNA ANALIZA KOLORYSTYCZNA ONLINE",
    title: "Odkryj kolory, w których naprawdę wyglądasz najlepiej.",
    subtitle: "Personalna analiza kolorystyczna na podstawie Twojego zdjęcia. Dowiedz się, jakie kolory ubrań, makijażu, włosów i biżuterii najlepiej podkreślają Twoją urodę — zamiast zgadywać przy kolejnych zakupach.",
    cta: "Odkryj swoją paletę — 39 zł",
    note: "1 zdjęcie · krótka analiza · personalny wynik od razu",
    secondaryCta: "Zobacz przykładowy wynik",
    heroPaletteLabel: "Twoja paleta",
    heroPaletteSample: [
      { name: "złamana biel", hex: "#F2EFE6" },
      { name: "czekoladowy brąz", hex: "#5B3B2E" },
      { name: "dusty rose", hex: "#B47D86" },
      { name: "petrol", hex: "#28636A" },
      { name: "leśna zieleń", hex: "#27513B" },
    ],

    whatYouGet: {
      eyebrow: "CO OTRZYMUJESZ",
      headline: "Nie tylko typ kolorystyczny. Dostajesz swoją osobistą ściągę do kolorów.",
      text: "Twoja analiza pokazuje nie tylko, które kolory Ci pasują, ale jak wykorzystać je w ubraniach, makijażu, biżuterii i przy wyborze koloru włosów.",
      items: [
        "Osobista paleta 12–20 kolorów",
        "4 najlepsze kolory neutralne",
        "3 kolory akcentowe",
        "Twoja idealna biel",
        "Twoja idealna czerń lub jej zamiennik",
        "Rekomendacja: złoto czy srebro",
        "3–5 kolorów makijażu",
        "Rekomendacje koloru włosów",
        "Kolory, na które warto uważać",
        "Przykładowa stylizacja",
      ],
      cards: ["Twój idealny biel", "Złoto czy srebro?", "Kolory makijażu", "Twoje najlepsze neutrale"],
    },

    benefits: {
      headline: "Kolory, które ułatwiają codzienne wybory.",
      items: [
        { title: "Łatwiejsze zakupy", text: "Wiesz, po jakie kolory sięgać i czego nie musisz nawet zabierać do przymierzalni." },
        { title: "Mniej nietrafionych ubrań", text: "Budujesz garderobę z kolorów, które rzeczywiście współpracują z Twoją urodą." },
        { title: "Makijaż bez zgadywania", text: "Łatwiej wybierasz odcienie różu, pomadki, cieni i innych kosmetyków." },
        { title: "Biżuteria i włosy", text: "Dowiadujesz się, czy bardziej służy Ci złoto czy srebro oraz jakie kierunki koloru włosów najlepiej współgrają z Twoją urodą." },
      ],
    },

    howItWorks: {
      eyebrow: "JAK POWSTAJE TWOJA ANALIZA",
      headline: "Każdy wynik zaczyna się od Ciebie.",
      text: "Łączymy informacje o Twojej urodzie ze zdjęciem referencyjnym, aby przygotować indywidualną paletę i rekomendacje, które możesz wykorzystać w praktyce.",
      steps: [
        { number: "01", label: "PROFIL", title: "Opowiedz nam o swojej urodzie", text: "Odpowiedz na pytania dotyczące swoich naturalnych cech. Pomagają one dokładniej określić kierunek analizy i właściwie interpretować zdjęcie." },
        { number: "02", label: "ZDJĘCIE", title: "Dodaj zdjęcie referencyjne", text: "Wyraźne zdjęcie twarzy w naturalnym świetle pozwala ocenić kolorystykę w możliwie neutralnych warunkach.", note: "Bez filtrów · w naturalnym świetle · zgodnie z prostą instrukcją" },
        { number: "03", label: "ANALIZA", title: "Otrzymaj indywidualne rekomendacje", text: "Na podstawie zebranych informacji otrzymujesz swoją paletę oraz wskazówki dotyczące ubrań, makijażu, biżuterii i koloru włosów.", note: "12–20 kolorów · neutrale · akcenty · biel i czerń · biżuteria · makijaż · włosy" },
      ],
      cta: "Odkryj swoją paletę — 39 zł",
      ctaNote: "Personalna analiza kolorystyczna online",
    },

    exampleResult: {
      eyebrow: "TWÓJ WYNIK",
      headline: "Twoja paleta to dopiero początek.",
      text: "Dowiesz się nie tylko, jakie kolory Ci służą, ale również jak wykorzystać je przy wyborze ubrań, makijażu, biżuterii i koloru włosów.",
      scopeLine: "12–20 kolorów · neutrale · akcenty · idealna biel · czerń lub jej zamiennik · biżuteria · makijaż · włosy",
      cta: "Odkryj swoją paletę — 39 zł",
      ctaNote: "Personalna analiza kolorystyczna online",
      cardEyebrow: "PRZYKŁADOWY FRAGMENT ANALIZY",
      cardLabel: "Twój kierunek kolorystyczny",
      cardTitle: "Ciepła Wiosna",
      cardText: "Świeże, ciepłe i świetliste odcienie, które harmonizują z Twoją naturalną kolorystyką.",
      palette: [
        { name: "koral", hex: "#E35B4F" },
        { name: "brzoskwiniowy", hex: "#E7A17E" },
        { name: "morelowy", hex: "#DD906A" },
        { name: "jasna oliwka", hex: "#A4A06F" },
        { name: "złocisty żółty", hex: "#D5A72E" },
        { name: "camel", hex: "#B88A57" },
        { name: "krem", hex: "#F2DFC2" },
        { name: "jasny turkus", hex: "#55B9B5" },
      ],
      modules: [
        { label: "Najlepsze neutrale", items: ["Kremowy", "Karmelowy", "Czekoladowy brąz", "Ciepły granat"] },
        { label: "Idealna biel", items: ["Kość słoniowa"] },
        { label: "Czerń", items: ["Zamiast czerni: głęboki brąz"] },
        { label: "Biżuteria", items: ["Złoto"] },
        { label: "Makijaż", items: ["Brzoskwiniowy róż", "Koral", "Ciepły róż", "Ciepły brąz"] },
        { label: "Włosy", items: ["Ciepłe brązy", "Miodowe refleksy", "Złociste odcienie"] },
      ],
      disclaimer: "To tylko fragment przykładowego wyniku. Twoja analiza zawiera pełną paletę i indywidualne rekomendacje.",
    },

    methodology: {
      headline: "Nie losujemy Twojej „pory roku”.",
      text: "Analiza uwzględnia indywidualne cechy Twojej urody, aby stworzyć rekomendacje dopasowane do Ciebie — nie tylko przypisać Cię do jednej ogólnej kategorii.",
    },

    credibility: {
      headline: "Created in Copenhagen.",
      text1: "Stworzone w Kopenhadze",
      text2: "Doświadczenie w technologii i analizie koloru, które stoi za tym projektem, obejmuje m.in. wykształcenie zdobyte w Copenhagen Business School.",
    },

    pricing: {
      insight1: "Jedna nietrafiona bluzka kosztuje więcej.",
      insight2: "Twoja paleta zostaje z Tobą przy kolejnych zakupach ubrań, kosmetyków, biżuterii i decyzjach dotyczących włosów.",
      cardTitle: "Personalna analiza kolorystyczna",
      price: "39 zł",
      includes: ["Osobista paleta kolorów", "Rekomendacje ubrań", "Rekomendacje makijażu", "Rekomendacja biżuterii", "Rekomendacje koloru włosów", "Wynik dostępny od razu"],
      cta: "Zrób swoją analizę — 39 zł",
    },

    faq: {
      headline: "Najczęstsze pytania",
      items: [
        { q: "Jakie zdjęcie najlepiej przesłać?", a: "Wyraźne zdjęcie twarzy zrobione w naturalnym, dziennym świetle, bez mocnego filtra." },
        { q: "Czy muszę być bez makijażu?", a: "Najlepiej bez makijażu lub z bardzo naturalnym makijażem — dzięki temu analiza lepiej odczytuje Twoją naturalną kolorystykę." },
        { q: "Czy mogę mieć farbowane włosy?", a: "Tak. W pytaniach uwzględniamy zarówno Twój naturalny, jak i obecny kolor włosów." },
        { q: "Czy wynik otrzymam od razu?", a: "Tak, wynik pojawia się od razu po zakończeniu analizy." },
        { q: "Co dokładnie dostanę w analizie?", a: "Pełną paletę kolorów, neutrale, akcenty, idealną biel i czerń, rekomendację złota lub srebra, kolory makijażu, rekomendacje koloru włosów oraz przykładową stylizację." },
        { q: "Czy analiza kosztuje tylko 39 zł?", a: "Tak, to jednorazowa opłata 39 zł bez ukrytych kosztów." },
        { q: "Co dzieje się z moim zdjęciem?", a: "Zdjęcie jest wykorzystywane wyłącznie do przygotowania Twojej analizy." },
      ],
    },

    finalCta: {
      eyebrow: "GOTOWA POZNAĆ SWOJE KOLORY?",
      headline: "Analiza, do której możesz wracać przy każdym kolejnym wyborze.",
      text: "Poznaj swoją paletę oraz rekomendacje dotyczące ubrań, makijażu, biżuterii i włosów.",
      cta: "Odkryj swoją paletę — 39 zł",
      ctaNote: "Personalna analiza kolorystyczna online",
    },
  },
  quiz: {
    eyebrow: "TWÓJ MAŁY PORTRET",
    progress: "Pytanie",
    of: "z",
    subtitle: "Wybierz odpowiedź, która najbardziej do Ciebie pasuje.",
  },
  photo: {
    eyebrow: "OSTATNI KROK",
    title: "Pokaż nam swoją naturalną stronę.",
    subtitle: "Dodaj wyraźne selfie, abyśmy mogły dobrać kolory do Twojej urody.",
    tipsTitle: "Najlepsze zdjęcie zrobisz tak:",
    tips: ["W dziennym świetle", "Bez makijażu", "Z widocznymi włosami", "Bez filtra"],
    upload: "Dodaj swoje zdjęcie",
    uploadHint: "Wybierz z galerii lub zrób zdjęcie telefonem",
    change: "Zmień zdjęcie",
    consent: "Zgadzam się na przetwarzanie mojego zdjęcia przez AI w celu wykonania analizy. Zdjęcie zostanie automatycznie usunięte po 24 godzinach.",
    submit: "Analizuj moje kolory",
    loadingTitle: "Szukamy Twoich kolorów…",
    loadingText: "Przyglądamy się detalom, które czynią Cię wyjątkową.",
    invalidFile: "Wybierz zdjęcie w formacie obrazu.",
  },
  result: {
    eyebrow: "TWOJA ANALIZA KOLORYSTYCZNA",
    teaserHeadline: "Twoja paleta jest gotowa",
    teaserSubtitle: "Oto pierwsze kolory z Twojej analizy. Pełny raport — z makijażem, włosami i przykładową stylizacją — czeka poniżej.",
    teaserPalette: "Pierwsze kolory z Twojej palety",
    hidden: "Twoja pełna paleta czeka na odkrycie",
    unlockTitle: "Poznaj całą swoją paletę.",
    unlockText: "Odkryj pełną paletę, dobór bieli, czerni i metalu, rekomendacje makijażu i włosów oraz przykładową stylizację.",
    legalConsent: "Zgadzam się na natychmiastowe dostarczenie treści cyfrowej i przyjmuję do wiadomości utratę 14-dniowego prawa do odstąpienia od umowy.",
    unlock: "Odblokuj pełny wynik – 39 zł",
    profileTitle: "Twój profil kolorystyczny",
    paletteTitle: "Twoja pełna paleta",
    baseTitle: "Kolory bazowe",
    accentsTitle: "Kolory akcentowe",
    whiteTitle: "Idealna biel",
    blackTitle: "Czerń i jej alternatywa",
    metalTitle: "Złoto czy srebro",
    makeupTitle: "Makijaż",
    makeupBlush: "Róż",
    makeupLips: "Usta",
    makeupEyes: "Oczy",
    makeupBronzer: "Bronzer",
    hairTitle: "Włosy",
    hairRecommended: "Warto rozważyć",
    hairAvoid: "Lepiej unikać",
    cautionTitle: "Kolory, z którymi warto uważać",
    outfitTitle: "Przykładowa stylizacja",
    download: "Pobierz kartę kolorów",
    downloadPlaceholder: "Pobieranie karty kolorów będzie dostępne wkrótce.",
    missing: "Nie znaleziono wyniku.",
    loading: "Otwieramy Twój wynik…",
    saveTitle: "Nie zgub swojej palety.",
    saveText: "Załóż darmowe konto, aby wracać do swojego wyniku w każdej chwili i na każdym urządzeniu.",
    saveSignup: "Załóż konto",
    saveLogin: "Mam już konto",
    saved: "Ten wynik jest zapisany na Twoim koncie.",
    savedLink: "Moje wyniki",
  },
  myResults: {
    metaTitle: "Moje wyniki — Twoje Kolory",
    eyebrow: "TWOJE KONTO",
    title: "Moje wyniki",
    subtitle: "Wszystkie Twoje analizy kolorystyczne w jednym miejscu.",
    loading: "Wczytujemy Twoje wyniki…",
    error: "Nie udało się wczytać wyników. Odśwież stronę i spróbuj ponownie.",
    empty: "Nie masz jeszcze żadnej analizy na swoim koncie.",
    emptyCta: "Zacznij test",
    paid: "Pełny wynik",
    locked: "Do odblokowania",
    open: "Zobacz wynik",
  },
  footer: {
    note: "Twoje kolory, po Twojemu.",
    tagline: "Personalna analiza kolorystyczna online.",
    contactLabel: "Kontakt",
    contactEmail: "info@twojcolor.com",
    techNote: "Analiza wspierana przez technologię AI.",
    copyright: "© 2026 Twoje Kolory. Wszystkie prawa zastrzeżone.",
  },
  legal: {
    terms: { label: "Regulamin", title: "Regulamin", text: "Ta strona jest wersją demonstracyjną. Pełny regulamin zostanie udostępniony przed uruchomieniem usługi." },
    privacy: { label: "Polityka prywatności", title: "Polityka prywatności", text: "Ta strona jest wersją demonstracyjną. Pełna polityka prywatności zostanie udostępniona przed uruchomieniem usługi." },
    cookies: { label: "Polityka cookies", title: "Polityka cookies", text: "Ta strona jest wersją demonstracyjną. Obecnie zapisujemy tylko Twój wybór dotyczący plików cookies w przeglądarce." },
    withdrawal: { label: "Odstąp od umowy", title: "Odstąp od umowy", text: "Ta strona jest wersją demonstracyjną. Informacje o odstąpieniu od umowy zostaną udostępnione przed uruchomieniem usługi." },
  },
  cookies: {
    title: "Dbamy o Twoją prywatność",
    text: "Używamy niezbędnych plików cookies. Możesz wybrać, czy zgadzasz się również na pozostałe.",
    accept: "Akceptuj wszystkie",
    necessary: "Tylko niezbędne",
  },
  auth: {
    navLogin: "Zaloguj się",
    navLogout: "Wyloguj się",
    navMyResults: "Moje wyniki",
    email: "E-mail",
    emailPlaceholder: "twoj@email.pl",
    password: "Hasło",
    passwordHint: "Co najmniej 8 znaków.",
    showPassword: "Pokaż hasło",
    hidePassword: "Ukryj hasło",
    login: {
      metaTitle: "Zaloguj się — Twoje Kolory",
      eyebrow: "WITAJ PONOWNIE",
      title: "Zaloguj się",
      subtitle: "Wróć do swojej palety kolorów.",
      submit: "Zaloguj się",
      forgot: "Nie pamiętasz hasła?",
      switchText: "Nie masz jeszcze konta?",
      switchLink: "Załóż konto",
    },
    signup: {
      metaTitle: "Załóż konto — Twoje Kolory",
      eyebrow: "TWOJE KONTO",
      title: "Załóż konto",
      subtitle: "Zapisz swoją paletę i wracaj do niej, kiedy tylko zechcesz.",
      consentBefore: "Akceptuję ",
      consentTerms: "Regulamin",
      consentAnd: " i ",
      consentPrivacy: "Politykę prywatności",
      consentAfter: ".",
      submit: "Załóż konto",
      switchText: "Masz już konto?",
      switchLink: "Zaloguj się",
    },
    verify: {
      metaTitle: "Potwierdź e-mail — Twoje Kolory",
      eyebrow: "JESZCZE JEDEN KROK",
      title: "Sprawdź swoją skrzynkę",
      sentTo: "Wysłałyśmy 6-cyfrowy kod na adres",
      codeLabel: "Kod weryfikacyjny",
      submit: "Potwierdź e-mail",
      resend: "Wyślij kod ponownie",
      resendIn: "Nowy kod wyślesz za",
      seconds: "s",
      resent: "Wysłałyśmy nowy kod. Sprawdź skrzynkę.",
      spamHint: "Nie widzisz wiadomości? Zajrzyj do folderu spam lub oferty.",
      wrongEmail: "Podałaś zły adres?",
      wrongEmailLink: "Załóż konto ponownie",
      missingEmail: "Brakuje adresu e-mail. Zaloguj się, aby otrzymać nowy kod.",
      recovery: {
        sentTo: "Jeśli konto z tym adresem istnieje, wysłałyśmy 6-cyfrowy kod na adres",
        submit: "Dalej",
        wrongEmail: "Podałaś zły adres?",
        wrongEmailLink: "Wpisz inny adres",
      },
    },
    forgot: {
      metaTitle: "Nie pamiętasz hasła? — Twoje Kolory",
      eyebrow: "NOWE HASŁO",
      title: "Nie pamiętasz hasła?",
      subtitle: "Podaj swój e-mail, a wyślemy Ci kod, dzięki któremu ustawisz nowe hasło.",
      submit: "Wyślij kod",
      back: "Wróć do logowania",
    },
    newPassword: {
      metaTitle: "Ustaw nowe hasło — Twoje Kolory",
      eyebrow: "NOWE HASŁO",
      title: "Ustaw nowe hasło",
      subtitle: "Wybierz hasło, którego będziesz od teraz używać przy logowaniu.",
      label: "Nowe hasło",
      submit: "Zapisz nowe hasło",
      expired: "Sesja zmiany hasła wygasła. Poproś o nowy kod.",
      expiredLink: "Wyślij nowy kod",
    },
    errors: {
      invalid_email: "Podaj prawidłowy adres e-mail.",
      password_too_short: "Hasło musi mieć co najmniej 8 znaków.",
      invalid_credentials: "Nieprawidłowy e-mail lub hasło.",
      email_not_confirmed: "Najpierw potwierdź swój adres e-mail.",
      weak_password: "To hasło jest zbyt łatwe do odgadnięcia. Wybierz inne.",
      same_password: "Nowe hasło musi się różnić od poprzedniego.",
      invalid_code: "Kod jest nieprawidłowy lub wygasł. Wyślij nowy kod.",
      rate_limited: "Zbyt wiele prób. Spróbuj ponownie za chwilę.",
      account_exists: "Konto z tym adresem już istnieje. Zaloguj się.",
      unknown: "Coś poszło nie tak. Spróbuj ponownie.",
    },
  },
};
