export const pl = {
  brand: "Twój Color",
  navStart: "Zrób analizę — 39 zł",
  navFaq: "FAQ",
  navMenu: "Menu",
  navHome: "Twój Color — strona główna",
  skipToContent: "Przejdź do treści",
  share: { label: "Udostępnij", copied: "Skopiowano link", copyFailed: "Skopiuj adres z paska przeglądarki" },
  breadcrumbsLabel: "Ścieżka nawigacji",
  notFound: {
    metaTitle: "Nie znaleziono strony — Twój Color",
    eyebrow: "Błąd 404",
    title: "Tego odcienia nie ma w naszej palecie.",
    text: "Strona, której szukasz, nie istnieje lub została przeniesiona. Wróć na stronę główną albo zajrzyj do przewodnika po typach urody.",
    home: "Strona główna",
    guide: "Przewodnik po typach urody",
    test: "Zrób analizę",
    seasonsLabel: "Popularne strony",
  },
  errorPage: {
    metaTitle: "Coś poszło nie tak — Twój Color",
    title: "Ta strona się nie wczytała.",
    text: "Wystąpił błąd po naszej stronie. Spróbuj odświeżyć stronę albo wróć na stronę główną.",
    retry: "Spróbuj ponownie",
    home: "Strona główna",
  },
  backHome: "Wróć na stronę główną",
  back: "Wstecz",
  next: "Dalej",
  landing: {
    meta: {
      title: "Twój Color — personalna analiza kolorystyczna online",
      description: "Dowiedz się, jakie kolory ubrań, makijażu, włosów i biżuterii najlepiej podkreślają Twoją urodę. Personalna analiza kolorystyczna online — 39 zł.",
    },
    cta: "Odkryj swoją paletę — 39 zł",
    ctaNote: "Personalna analiza kolorystyczna online",
    hero: {
      eyebrow: "Personalna analiza kolorystyczna online",
      titlePrefix: "Odkryj kolory, w których naprawdę wyglądasz ",
      titleHighlight: "najlepiej.",
      lead: "Dowiedz się, jakie kolory ubrań, makijażu, włosów i biżuterii najlepiej podkreślają Twoją urodę - nie zgaduj przy następnych zakupach.",
      meta: "1 zdjęcie · ok. 60 sekund · personalny wynik od razu",
      imageAlt: "Uśmiechnięta kobieta o ciepłej karnacji i brązowych włosach na beżowym tle",
    },
    includes: {
      eyebrow: "Twoja osobista ściąga kolorów.",
      headline: "Co otrzymujesz w analizie?",
      lead: "Twoja analiza pokazuje nie tylko, które kolory Ci pasują, ale jak wykorzystać je w ubraniach, makijażu, biżuterii i przy wyborze koloru włosów.",
      items: [
        "Paleta 12–20 kolorów",
        "4 najlepsze neutralne kolory",
        "3 kolory akcentowe",
        "Twój idealny odcień bieli",
        "Twoja idealna czerń lub jej najlepszy zamiennik",
        "Złoto vs. srebro",
        "3–5 kolorów makijażu",
        "Rekomendacje koloru włosów",
        "Kolory, z którymi warto uważać",
        "Przykładowy outfit",
      ],
      cards: {
        black: "Idealna czerń i biel",
        gold: "Złoto czy srebro?",
        lips: "Kolory makijażu",
        neutral: "Neutrale",
      },
    },
    process: {
      eyebrow: "Jak powstaje Twoja analiza",
      headlinePrefix: "Każdy wynik jest ",
      headlineHighlight: "personalnie",
      headlineSuffix: " dobrany do twoich cech",
      lead: "Łączymy informacje o Twojej urodzie ze zdjęciem referencyjnym, aby przygotować indywidualną paletę i rekomendacje, które możesz wykorzystać w praktyce.",
      steps: [
        { number: "01", tag: "Profil", title: "Opowiedz nam o swojej urodzie", text: "Odpowiedz na pytania dotyczące swoich naturalnych cech. Pomagają one dokładniej określić kierunek analizy i właściwie interpretować zdjęcie.", note: null },
        { number: "02", tag: "Zdjęcie", title: "Dodaj zdjęcie referencyjne", text: "Wyraźne zdjęcie twarzy w naturalnym świetle pozwala ocenić kolorystykę w możliwie neutralnych warunkach.", note: "Bez filtrów · w naturalnym świetle · zgodnie z prostą instrukcją" },
        { number: "03", tag: "Analiza", title: "Otrzymaj indywidualne rekomendacje", text: "Na podstawie zebranych informacji otrzymujesz swoją paletę oraz wskazówki dotyczące ubrań, makijażu, biżuterii i koloru włosów.", note: "12–20 kolorów · neutrale · akcenty · biel i czerń" },
      ],
    },
    result: {
      eyebrow: "Twój wynik",
      headline: "Twoja paleta to dopiero początek.",
      lead: "Wynik pokazuje nie tylko kolory, które Ci służą. Otrzymujesz również wskazówki dotyczące neutralnych baz, akcentów, bieli i czerni, biżuterii, makijażu oraz koloru włosów.",
      report: {
        ariaLabel: "Przykładowy fragment analizy: Ciepła Wiosna",
        eyebrow: "Przykładowy fragment analizy",
        title: "Ciepła Wiosna",
        description: "Jasna, ciepła i lekko złota kolorystyka, która harmonizuje z Twoją naturalną urodą. Wybieramy kolory najcieplejsze, mocno nasycone z palety klasycznej wiosny oraz kradniemy kilka ciepłych, przygaszonych barw z palety jesieni. Kolory jaskrawe i zimne oraz jasne i zimne będą poszarzały cerę lub przytłaczały Ciepłą Wiosnę.",
        paletteLabel: "Paleta kolorów",
        palette: ["#e0475e", "#e86f74", "#eaaf93", "#fae6c8", "#e3ba7a", "#8f5f45", "#856c4b", "#c1d47b", "#a9c247", "#b98bbf"],
        neutrals: {
          title: "Neutrale",
          colors: [
            { name: "Kość słoniowa", hex: "#fcf6ea" },
            { name: "Ciepły beż", hex: "#e4cba7" },
            { name: "Camel", hex: "#c69866" },
            { name: "Kakao", hex: "#8b5f45" },
          ],
          foot: "Biel: ecru • Zamiast czerni: ciepły brąz",
        },
        accents: {
          title: "Kolory akcentowe",
          colors: [
            { name: "Koral", hex: "#fc6450" },
            { name: "Turkus", hex: "#3dbcb3" },
            { name: "Zieleń liści", hex: "#8fc04f" },
          ],
        },
        jewelry: { title: "Biżuteria", alt: "Złote kolczyki koła, naszyjnik z medalionem i próbki złota", foot: ["Żółte złoto • Szampańskie złoto", "Ciepłe, świetliste wykończenie"] },
        makeup: { title: "Makijaż", alt: "Koralowa szminka, brzoskwiniowy róż i złoto-karmelowe cienie", captions: ["Usta: koral", "Róż: brzoskwinia", "Oczy: złoto i karmel"] },
        hair: { title: "Kolory włosów", alt: "Pasma włosów: złoty blond, miodowy blond, jasna miedź", captions: ["Złoty blond", "Miodowy blond", "Jasna miedź"], foot: "Unikaj chłodnych, popielatych tonów" },
        outfit: { title: "Przykładowa stylizacja", alt: "Ecru koszula, spodnie w kolorze camel i koralowa torebka", foot: "Ecru + camel + koral" },
      },
    },
    compare: {
      eyebrow: "Dlaczego kolory mają znaczenie",
      headline: ["Mała zmiana koloru.", "Duża różnica w odbiorze."],
      sub: "Zobacz, jak odcienie noszone blisko twarzy mogą podkreślić Twoją naturalną urodę.",
      bad: {
        title: "Przypadkowe odcienie",
        alt: "Kobieta w fioletowo-szarym szalu, który przytłacza jej rysy",
        fabricsLabel: "Przykładowe odcienie: grafit, śliwka, chłodny róż",
        fabrics: ["Tkanina w kolorze grafitowym", "Tkanina w kolorze śliwkowym", "Tkanina w chłodnym różu"],
        items: ["Kolor może przytłaczać rysy", "Cienie mogą wydawać się wyraźniejsze", "Odcienie trudniej ze sobą łączyć", "Zakupy częściej kończą się przypadkiem"],
      },
      good: {
        title: "Kolory w harmonii z Tobą",
        alt: "Ta sama kobieta w koralowym szalu, który rozświetla cerę",
        fabricsLabel: "Przykładowe odcienie: ecru, koral, morska zieleń",
        fabrics: ["Tkanina w kolorze ecru", "Tkanina w kolorze koralowym", "Tkanina w kolorze morskiej zieleni"],
        items: ["Naturalne rysy zyskują wyrazistość", "Cera może wyglądać bardziej świeżo", "Ubrania tworzą spójną paletę", "Łatwiej wybierać pasujące odcienie"],
      },
      note: "* O efekcie decyduje indywidualny dobór odcieni",
    },
    seasons: {
      eyebrow: "Odkryj swoją paletę",
      headline: ["Poznaj 12 typów urody", "i ich idealne kolory"],
      sub: "Wybierz porę roku i odkryj odcienie, które harmonizują z Twoją urodą.",
      seasonGroupLabel: "Pora roku",
      typeGroupLabel: "Typ urody",
      cardEyebrow: "Paleta przykładowa",
      comboLabel: "Pomysł na połączenie",
      mediaAlt: "Stylizacja: ecru jedwabna koszula, miętowa torebka, brzoskwiniowe spodnie i złote kolczyki",
      mediaCaption: "Kolory w codziennej stylizacji",
      cta: "Zobacz pełny przewodnik",
      allTypes: "Wszystkie 12 typów urody",
      list: [
        {
          key: "wiosna",
          label: "Wiosna",
          types: [
            { key: "jasna-wiosna", label: "Jasna Wiosna", chips: ["Jasna", "Delikatnie ciepła", "Świeża"], description: "Świetliste, lekkie odcienie z ciepłą nutą. Subtelne zestawienia podkreślają urodę bez mocnych kontrastów.", swatches: [{ name: "Brzoskwinia", hex: "#fdcfae" }, { name: "Mięta", hex: "#b4ecc5" }, { name: "Akwamaryn", hex: "#b5e1e1" }, { name: "Jasny koral", hex: "#ffabab" }, { name: "Wanilia", hex: "#fde99a" }], combo: { colors: ["#fcf6ea", "#fdcfae", "#b4ecc5"], text: "Ecru + brzoskwinia + mięta" } },
            { key: "ciepla-wiosna", label: "Ciepła Wiosna", chips: ["Ciepła", "Złocista", "Nasycona"], description: "Jasna, ciepła i lekko złota kolorystyka. Najlepiej wyglądasz w nasyconych, słonecznych odcieniach.", swatches: [{ name: "Koral", hex: "#fc6450" }, { name: "Turkus", hex: "#3dbcb3" }, { name: "Camel", hex: "#c69866" }, { name: "Zieleń liści", hex: "#8fc04f" }, { name: "Złoto", hex: "#e3ba7a" }], combo: { colors: ["#fcf6ea", "#c69866", "#fc6450"], text: "Ecru + camel + koral" } },
            { key: "czysta-wiosna", label: "Czysta Wiosna", chips: ["Czysta", "Kontrastowa", "Żywa"], description: "Jasne, czyste i żywe kolory z wyraźnym kontrastem. Rozświetlają cerę i dodają energii.", swatches: [{ name: "Maków czerwień", hex: "#e8384f" }, { name: "Turkus", hex: "#14b8b0" }, { name: "Żonkil", hex: "#ffd23f" }, { name: "Kobalt", hex: "#2f6fd6" }, { name: "Limonka", hex: "#9fd83b" }], combo: { colors: ["#ffffff", "#14b8b0", "#ffd23f"], text: "Biel + turkus + żonkil" } },
          ],
        },
        {
          key: "lato",
          label: "Lato",
          types: [
            { key: "jasne-lato", label: "Jasne Lato", chips: ["Jasne", "Chłodne", "Delikatne"], description: "Pastelowe, chłodne odcienie o miękkim charakterze. Delikatne zestawienia harmonizują z jasną cerą.", swatches: [{ name: "Pudrowy róż", hex: "#f4c6d0" }, { name: "Lawenda", hex: "#c9bde6" }, { name: "Błękit", hex: "#b6d4ee" }, { name: "Szałwia", hex: "#bcd3c2" }, { name: "Perła", hex: "#eeeae4" }], combo: { colors: ["#eeeae4", "#f4c6d0", "#b6d4ee"], text: "Perła + pudrowy róż + błękit" } },
            { key: "chlodne-lato", label: "Chłodne Lato", chips: ["Chłodne", "Średnie", "Eleganckie"], description: "Chłodne, średnio nasycone kolory z niebieskim tonem. Sprawdzają się w eleganckich, spokojnych stylizacjach.", swatches: [{ name: "Malina", hex: "#c8547c" }, { name: "Morski", hex: "#4f8aa8" }, { name: "Szaroniebieski", hex: "#8ea4bf" }, { name: "Śliwka", hex: "#8a5c8a" }, { name: "Grafit", hex: "#5e6670" }], combo: { colors: ["#8ea4bf", "#c8547c", "#5e6670"], text: "Szaroniebieski + malina + grafit" } },
            { key: "zgaszone-lato", label: "Zgaszone Lato", chips: ["Zgaszone", "Miękkie", "Chłodnawe"], description: "Przygaszone, przydymione odcienie bez ostrych kontrastów. Dają efekt naturalnej elegancji.", swatches: [{ name: "Brudny róż", hex: "#c99aa0" }, { name: "Szałwia", hex: "#9fb09f" }, { name: "Mgła", hex: "#a9b4bf" }, { name: "Taupe", hex: "#9b8c84" }, { name: "Wrzos", hex: "#a28ca8" }], combo: { colors: ["#a9b4bf", "#c99aa0", "#9b8c84"], text: "Mgła + brudny róż + taupe" } },
          ],
        },
        {
          key: "jesien",
          label: "Jesień",
          types: [
            { key: "zgaszona-jesien", label: "Zgaszona Jesień", chips: ["Zgaszona", "Ciepła", "Naturalna"], description: "Miękkie, ziemiste kolory o ciepłym tonie. Tworzą spokojne, naturalne zestawienia.", swatches: [{ name: "Khaki", hex: "#a39a6d" }, { name: "Łosoś", hex: "#d99a80" }, { name: "Mech", hex: "#7d8a5a" }, { name: "Karmel", hex: "#b7834f" }, { name: "Piasek", hex: "#d6c3a0" }], combo: { colors: ["#d6c3a0", "#7d8a5a", "#d99a80"], text: "Piasek + mech + łosoś" } },
            { key: "ciepla-jesien", label: "Ciepła Jesień", chips: ["Ciepła", "Bogata", "Złota"], description: "Bogate, ciepłe odcienie przypraw i jesiennych liści. Podkreślają złoty ton skóry.", swatches: [{ name: "Rdza", hex: "#b5532c" }, { name: "Musztarda", hex: "#d6a12a" }, { name: "Oliwka", hex: "#6f7a34" }, { name: "Terakota", hex: "#c06a45" }, { name: "Czekolada", hex: "#6a3f2a" }], combo: { colors: ["#f3e3c6", "#b5532c", "#6f7a34"], text: "Krem + rdza + oliwka" } },
            { key: "gleboka-jesien", label: "Głęboka Jesień", chips: ["Głęboka", "Ciepła", "Intensywna"], description: "Ciemne, nasycone kolory z ciepłym podtonem. Dodają wyrazistości ciemniejszej urodzie.", swatches: [{ name: "Bordo", hex: "#7a2533" }, { name: "Butelkowa", hex: "#2f5a45" }, { name: "Bakłażan", hex: "#4f2c3f" }, { name: "Miedź", hex: "#a8582e" }, { name: "Espresso", hex: "#3d2a22" }], combo: { colors: ["#3d2a22", "#a8582e", "#2f5a45"], text: "Espresso + miedź + butelkowa zieleń" } },
          ],
        },
        {
          key: "zima",
          label: "Zima",
          types: [
            { key: "gleboka-zima", label: "Głęboka Zima", chips: ["Głęboka", "Chłodna", "Kontrastowa"], description: "Ciemne, chłodne kolory z mocnym kontrastem. Czerń i głębokie klejnoty wyglądają naturalnie.", swatches: [{ name: "Czerń", hex: "#1d1b1f" }, { name: "Rubin", hex: "#9b1b3a" }, { name: "Szmaragd", hex: "#0f6b52" }, { name: "Granat", hex: "#1f2f5a" }, { name: "Śliwka", hex: "#4c1f4a" }], combo: { colors: ["#1d1b1f", "#ffffff", "#9b1b3a"], text: "Czerń + biel + rubin" } },
            { key: "chlodna-zima", label: "Chłodna Zima", chips: ["Chłodna", "Czysta", "Lodowa"], description: "Czyste, chłodne odcienie z niebieskim tonem. Lodowe pastele i mocne akcenty tworzą efektowne pary.", swatches: [{ name: "Fuksja", hex: "#c4287a" }, { name: "Królewski", hex: "#2347a8" }, { name: "Lodowy błękit", hex: "#cfe6f5" }, { name: "Sosna", hex: "#1e5a4c" }, { name: "Srebro", hex: "#c3c7cc" }], combo: { colors: ["#cfe6f5", "#2347a8", "#c4287a"], text: "Lodowy błękit + królewski + fuksja" } },
            { key: "czysta-zima", label: "Czysta Zima", chips: ["Czysta", "Jaskrawa", "Wyrazista"], description: "Najbardziej żywe i kontrastowe kolory w palecie. Czysta biel i intensywne barwy podkreślają rysy.", swatches: [{ name: "Czysta biel", hex: "#ffffff" }, { name: "Karmazyn", hex: "#d0103a" }, { name: "Kobalt", hex: "#0047ab" }, { name: "Cytryna", hex: "#f6e83a" }, { name: "Ametyst", hex: "#7b3fa0" }], combo: { colors: ["#ffffff", "#0047ab", "#d0103a"], text: "Biel + kobalt + karmazyn" } },
          ],
        },
      ],
    },
    faq: {
      eyebrow: "Warto wiedzieć",
      headline: "Często zadawane pytania",
      sub: "Wszystko, co warto wiedzieć przed odkryciem swojej palety.",
      items: [
        { q: "Mam farbowane włosy — czy analiza ma sens?", a: "Tak. Przy ocenie kolorystyki ważne są również odcień skóry, kolor oczu i naturalny kolor włosów. W formularzu podaj swój naturalny odcień, a do zdjęcia odsuń farbowane pasma od twarzy." },
        { q: "Czy muszę znać się na modzie lub kolorach?", a: "Nie. Wynik jest napisany prostym językiem, z gotowymi przykładami połączeń, dzięki czemu od razu wiesz, jak wykorzystać swoją paletę." },
        { q: "Jak przygotować zdjęcie do analizy?", a: "Zrób zdjęcie twarzy przy oknie, w naturalnym świetle dziennym, bez filtrów i mocnego makijażu. Odsuń włosy od twarzy i stań na tle neutralnej ściany." },
        { q: "Ile czasu zajmuje wykonanie analizy?", a: "Wypełnienie krótkiego formularza i dodanie zdjęcia zajmuje kilka minut, a sam wynik otrzymujesz w około 60 sekund." },
        { q: "Co otrzymam w swoim wyniku?", a: "Paletę 12–20 kolorów, neutrale i akcenty, idealną biel i czerń, rekomendacje biżuterii, makijażu i koloru włosów oraz przykładowy outfit." },
        { q: "Ile kosztuje pełna analiza?", a: "Pełna analiza kosztuje 39 zł. To jednorazowa opłata — bez subskrypcji i ukrytych kosztów." },
        { q: "Jak dokładna jest analiza ze zdjęcia?", a: "Łączymy ocenę zdjęcia z odpowiedziami o Twoich naturalnych cechach, co znacząco zwiększa trafność wyniku. Kluczowe jest dobre, naturalne światło." },
        { q: "Czy mogę wykonać analizę na telefonie?", a: "Tak. Cały proces — od formularza po zdjęcie i wynik — działa w przeglądarce na telefonie, bez instalowania aplikacji." },
      ],
      ctaText: "Poznaj kolory, po które będziesz sięgać z przyjemnością.",
      cta: "Odkryj swoją paletę",
    },
  },
  quiz: {
    eyebrow: "TWÓJ MAŁY PORTRET",
    progress: "Pytanie",
    of: "z",
    subtitle: "Wybierz odpowiedź, która najbardziej do Ciebie pasuje.",
  },
  photo: {
    eyebrow: "OSTATNI KROK",
    title: "Pokaż nam swoją naturalną stronę.",
    subtitle: "Dodaj wyraźne selfie, abyśmy mogły dobrać kolory do Twojej urody.",
    tipsTitle: "Najlepsze zdjęcie zrobisz tak:",
    tips: ["W dziennym świetle", "Bez makijażu", "Z widocznymi włosami", "Bez filtra"],
    upload: "Dodaj swoje zdjęcie",
    uploadHint: "Wybierz z galerii lub zrób zdjęcie telefonem",
    change: "Zmień zdjęcie",
    consent: "Zgadzam się na przetwarzanie mojego zdjęcia przez AI w celu wykonania analizy. Zdjęcie zostanie automatycznie usunięte po 24 godzinach.",
    submit: "Analizuj moje kolory",
    loadingTitle: "Szukamy Twoich kolorów…",
    loadingText: "Przyglądamy się detalom, które czynią Cię wyjątkową.",
    invalidFile: "Wybierz zdjęcie w formacie obrazu.",
  },
  result: {
    eyebrow: "TWOJA ANALIZA KOLORYSTYCZNA",
    teaserHeadline: "Twoja paleta jest gotowa",
    teaserSubtitle: "Oto pierwsze kolory z Twojej analizy. Pełny raport — z makijażem, włosami i przykładową stylizacją — czeka poniżej.",
    teaserPalette: "Pierwsze kolory z Twojej palety",
    hidden: "Twoja pełna paleta czeka na odkrycie",
    unlockTitle: "Poznaj całą swoją paletę.",
    unlockText: "Odkryj pełną paletę, dobór bieli, czerni i metalu, rekomendacje makijażu i włosów oraz przykładową stylizację.",
    legalConsent: "Zgadzam się na natychmiastowe dostarczenie treści cyfrowej i przyjmuję do wiadomości utratę 14-dniowego prawa do odstąpienia od umowy.",
    unlock: "Odblokuj pełny wynik – 39 zł",
    profileTitle: "Twój profil kolorystyczny",
    paletteTitle: "Twoja pełna paleta",
    baseTitle: "Kolory bazowe",
    accentsTitle: "Kolory akcentowe",
    whiteTitle: "Idealna biel",
    blackTitle: "Czerń i jej alternatywa",
    metalTitle: "Złoto czy srebro",
    makeupTitle: "Makijaż",
    makeupBlush: "Róż",
    makeupLips: "Usta",
    makeupEyes: "Oczy",
    makeupBronzer: "Bronzer",
    hairTitle: "Włosy",
    hairRecommended: "Warto rozważyć",
    hairAvoid: "Lepiej unikać",
    cautionTitle: "Kolory, z którymi warto uważać",
    outfitTitle: "Przykładowa stylizacja",
    download: "Pobierz kartę kolorów",
    downloadPlaceholder: "Pobieranie karty kolorów będzie dostępne wkrótce.",
    missing: "Nie znaleziono wyniku.",
    loading: "Otwieramy Twój wynik…",
    saveTitle: "Nie zgub swojej palety.",
    saveText: "Załóż darmowe konto, aby wracać do swojego wyniku w każdej chwili i na każdym urządzeniu.",
    saveSignup: "Załóż konto",
    saveLogin: "Mam już konto",
    saved: "Ten wynik jest zapisany na Twoim koncie.",
    savedLink: "Moje wyniki",
  },
  myResults: {
    metaTitle: "Moje wyniki — Twój Color",
    eyebrow: "TWOJE KONTO",
    title: "Moje wyniki",
    subtitle: "Wszystkie Twoje analizy kolorystyczne w jednym miejscu.",
    loading: "Wczytujemy Twoje wyniki…",
    error: "Nie udało się wczytać wyników. Odśwież stronę i spróbuj ponownie.",
    empty: "Nie masz jeszcze żadnej analizy na swoim koncie.",
    emptyCta: "Zacznij test",
    resultLabel: "Analiza kolorystyczna",
    paid: "Pełny wynik",
    locked: "Do odblokowania",
    open: "Zobacz wynik",
  },
  footer: {
    note: "Twoje kolory, po Twojemu.",
    tagline: "Personalna analiza kolorystyczna online.",
    contactLabel: "Kontakt",
    guideLabel: "Przewodnik",
    guideAll: "12 typów urody",
    legalLabel: "Informacje prawne",
    contactEmail: "info@twojcolor.com",
    techNote: "Analiza wspierana przez technologię AI.",
    copyright: "© 2026 Twój Color. Wszystkie prawa zastrzeżone.",
  },
  legal: {
    terms: { label: "Regulamin", title: "Regulamin", text: "Ta strona jest wersją demonstracyjną. Pełny regulamin zostanie udostępniony przed uruchomieniem usługi." },
    privacy: { label: "Polityka prywatności", title: "Polityka prywatności", text: "Ta strona jest wersją demonstracyjną. Pełna polityka prywatności zostanie udostępniona przed uruchomieniem usługi." },
    cookies: { label: "Polityka cookies", title: "Polityka cookies", text: "Ta strona jest wersją demonstracyjną. Obecnie zapisujemy tylko Twój wybór dotyczący plików cookies w przeglądarce." },
    withdrawal: { label: "Odstąp od umowy", title: "Odstąp od umowy", text: "Ta strona jest wersją demonstracyjną. Informacje o odstąpieniu od umowy zostaną udostępnione przed uruchomieniem usługi." },
  },
  cookies: {
    title: "Dbamy o Twoją prywatność",
    text: "Używamy niezbędnych plików cookies. Możesz wybrać, czy zgadzasz się również na pozostałe.",
    accept: "Akceptuj wszystkie",
    necessary: "Tylko niezbędne",
  },
  auth: {
    navLogin: "Zaloguj się",
    navLogout: "Wyloguj się",
    navMyResults: "Moje wyniki",
    email: "E-mail",
    emailPlaceholder: "twoj@email.pl",
    password: "Hasło",
    passwordHint: "Co najmniej 8 znaków.",
    showPassword: "Pokaż hasło",
    hidePassword: "Ukryj hasło",
    login: {
      metaTitle: "Zaloguj się — Twój Color",
      eyebrow: "WITAJ PONOWNIE",
      title: "Zaloguj się",
      subtitle: "Wróć do swojej palety kolorów.",
      submit: "Zaloguj się",
      forgot: "Nie pamiętasz hasła?",
      switchText: "Nie masz jeszcze konta?",
      switchLink: "Załóż konto",
    },
    signup: {
      metaTitle: "Załóż konto — Twój Color",
      eyebrow: "TWOJE KONTO",
      title: "Załóż konto",
      subtitle: "Zapisz swoją paletę i wracaj do niej, kiedy tylko zechcesz.",
      consentBefore: "Akceptuję ",
      consentTerms: "Regulamin",
      consentAnd: " i ",
      consentPrivacy: "Politykę prywatności",
      consentAfter: ".",
      submit: "Załóż konto",
      switchText: "Masz już konto?",
      switchLink: "Zaloguj się",
    },
    verify: {
      metaTitle: "Potwierdź e-mail — Twój Color",
      eyebrow: "JESZCZE JEDEN KROK",
      title: "Sprawdź swoją skrzynkę",
      sentTo: "Wysłałyśmy 6-cyfrowy kod na adres",
      codeLabel: "Kod weryfikacyjny",
      submit: "Potwierdź e-mail",
      resend: "Wyślij kod ponownie",
      resendIn: "Nowy kod wyślesz za",
      seconds: "s",
      resent: "Wysłałyśmy nowy kod. Sprawdź skrzynkę.",
      spamHint: "Nie widzisz wiadomości? Zajrzyj do folderu spam lub oferty.",
      wrongEmail: "Podałaś zły adres?",
      wrongEmailLink: "Załóż konto ponownie",
      missingEmail: "Brakuje adresu e-mail. Zaloguj się, aby otrzymać nowy kod.",
      recovery: {
        sentTo: "Jeśli konto z tym adresem istnieje, wysłałyśmy 6-cyfrowy kod na adres",
        submit: "Dalej",
        wrongEmail: "Podałaś zły adres?",
        wrongEmailLink: "Wpisz inny adres",
      },
    },
    forgot: {
      metaTitle: "Nie pamiętasz hasła? — Twój Color",
      eyebrow: "NOWE HASŁO",
      title: "Nie pamiętasz hasła?",
      subtitle: "Podaj swój e-mail, a wyślemy Ci kod, dzięki któremu ustawisz nowe hasło.",
      submit: "Wyślij kod",
      back: "Wróć do logowania",
    },
    newPassword: {
      metaTitle: "Ustaw nowe hasło — Twój Color",
      eyebrow: "NOWE HASŁO",
      title: "Ustaw nowe hasło",
      subtitle: "Wybierz hasło, którego będziesz od teraz używać przy logowaniu.",
      label: "Nowe hasło",
      submit: "Zapisz nowe hasło",
      expired: "Sesja zmiany hasła wygasła. Poproś o nowy kod.",
      expiredLink: "Wyślij nowy kod",
    },
    errors: {
      invalid_email: "Podaj prawidłowy adres e-mail.",
      password_too_short: "Hasło musi mieć co najmniej 8 znaków.",
      invalid_credentials: "Nieprawidłowy e-mail lub hasło.",
      email_not_confirmed: "Najpierw potwierdź swój adres e-mail.",
      weak_password: "To hasło jest zbyt łatwe do odgadnięcia. Wybierz inne.",
      same_password: "Nowe hasło musi się różnić od poprzedniego.",
      invalid_code: "Kod jest nieprawidłowy lub wygasł. Wyślij nowy kod.",
      rate_limited: "Zbyt wiele prób. Spróbuj ponownie za chwilę.",
      account_exists: "Konto z tym adresem już istnieje. Zaloguj się.",
      unknown: "Coś poszło nie tak. Spróbuj ponownie.",
    },
  },
};
